<?php

namespace App\Console\Commands;

use App\Exceptions\RenderableException;
use App\Model\Master\Client;
use App\Model\MysqlConnections;
use Illuminate\Console\Command;

class CreateDatabaseConfig extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'make:database:config';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Creates config/database.php file from clients table';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->info("Building client DB connections from master.clients + master.mysql_connections");

        $clientConnections = [];

        $clients = Client::all();
        foreach ($clients as $client) {
            $connection = MysqlConnections::where("client_id", "=", $client->id)->first();
            if (empty($connection)) {
                $this->warn("Skipping client_id {$client->id} — no entry in mysql_connections");
                continue;
            }

            $entry = [
                'driver'    => 'mysql',
                'host'      => $connection->ip,
                'database'  => $connection->db_name,
                'username'  => $connection->db_user,
                'password'  => $connection->password,
                'charset'   => 'utf8mb4',
                'collation' => 'utf8mb4_unicode_ci',
                'strict'    => false,
                'timezone'  => '+00:00',
            ];

            $clientConnections["mysql_{$client->id}"] = $entry;

            // Register connection in running config immediately
            config(["database.connections.mysql_{$client->id}" => $entry]);
        }

        // Write ONLY client connections to a separate file.
        // The master connection in config/database.php always reads from .env.
        $connectionsFile = app()->basePath() . '/config/database_clients.php';
        $fp = fopen($connectionsFile, 'w');
        fwrite($fp, "<?php\n// Auto-generated by make:database:config — do NOT commit.\n// Contains per-client DB credentials. Included by config/database.php\nreturn " . var_export($clientConnections, true) . ";\n");
        fclose($fp);

        $this->info("Written " . count($clientConnections) . " client connections to config/database_clients.php");
        $this->info("Client IDs: " . implode(", ", array_keys($clientConnections)));
    }
}
